### ISSUE TITLE
Process completed with exit code 1.

### ISSUE THREAD

**Issue by jr-django** [php-actions/phpstan#24]
hello, the file is being created like this, but I'm getting an error. why am I getting errors in the new version in this way? how can I fix it.

------

![image](https://user-images.githubusercontent.com/130409982/235862488-15d6e5d8-d189-41c3-8c3b-3b23b9045c55.png)

----

Error message:

![image](https://user-images.githubusercontent.com/130409982/235861701-ca779272-d47e-42e8-8d84-9143f39b6751.png)

**Comment by g105b** [comment]
Hi, yes... there has been an update that I'm going to revert. You can fix your version by using `php-actions/phpstan@v3.0.2`

**Comment by g105b** [comment]
Thanks for letting me know. The release was made too much in haste, so I reverted it. I didn't think it would affect other codebases, but I will be more careful! Sorry to cause some downtime for you.
