### ISSUE TITLE
phpstan Error

### ISSUE THREAD

**Issue by jr-django** [php-actions/phpstan#25]
hello good day @g105b .

i have a utility functions file. I also have a helper method for the user model in this file. phpstan gives the following error when analyzing.

Call to static method findOrFail() on an unknown class App\Models\User.

![image](https://github.com/php-actions/phpstan/assets/130409982/656fa314-81eb-4095-a082-3c363ab89fe7)

![image](https://github.com/php-actions/phpstan/assets/130409982/eab4149c-eff3-408d-ba4a-0f70825aa9f0)

Workflows file content :

![image](https://github.com/php-actions/phpstan/assets/130409982/6e4176ca-fe5c-4763-9924-fa667e54abb6)

how can I solve this problem.

**Comment by g105b** [comment]
The first thing that jumps out to me is whether or not the `composer.json` defines the autoload path correctly for the `App\Model\` namespace. Does the namespace for this class match the PSR-0 or PSR-4 standard?

**Comment by g105b** [comment]
Yeah, otherwise you will need to create your own autoloader, and include it as part of the PHPStan bootstrapping process - its much easier in the composer.json because it's all handled for you and standardised.
