### ISSUE TITLE
Invalid link in README.me

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [php-actions/phpstan#4]
README.md contains the link to https://github.com/php-actions/example-phpstan, however there is no such repo

https://github.com/php-actions/phpstan/blame/master/README.md#L32

**Comment by g105b** [comment]
Oops, I'm ahead of myself! I'll create the repository tonight with some example code so we've got a reference repo.

**Comment by g105b** [comment]
Her eyou go: https://github.com/php-actions/example-phpstan/actions/runs/630478522

Have fun!
