### ISSUE TITLE
Copy&Paste in README?

### ISSUE THREAD

**Issue by MarcinOrlowski** [php-actions/phpstan#6]
README says in line 45:

    version The version of PHPUnit to use e.g. 9 or 9.5.0 (default: latest)

shouldn't it refer to PHPStan version instead?

**Comment by g105b** [comment]
Yep! Thanks for pointing this out - I had made the PHPUnit repository first, and I copied the readme over from there to edit accordingly - but as you've found, I missed a vital piece of information.

Will update later today.
