### ISSUE TITLE
Docs improvement for `path` with multiuple paths

### ISSUE THREAD

**Issue by MarcinOrlowski** [php-actions/phpstan#7]
Would be handy to have examples for i.e.

    path Path(s) with source code to run analysis on (required)

showing the example of defining also multiple paths

**Comment by g105b** [comment]
Thanks. I'll add an example to https://github.com/php-actions/example-phpstan for this purpose when I get to the code later today.

**Comment by MDSLKTR** [comment]
Could you post an example how to set multiple paths?

**Comment by g105b** [comment]
Hi, I've just been through and tested this - the solution was to use spaces, yes - but I've added some extra code to handle directories with space names in.

See here: https://github.com/php-actions/example-phpstan/blob/master/.github/workflows/ci.yml#L15

Working action: https://github.com/php-actions/example-phpstan/runs/5124500497?check_suite_focus=true
