### ISSUE TITLE
"/usr/local/bin/phpstan: line 2: syntax error: unexpected newline"

### ISSUE THREAD

**Issue by MarcinOrlowski** [php-actions/phpstan#8]
Out of sudden I started to face

```
Run php-actions/phpstan@v3
/usr/local/bin/phpstan: line 2: syntax error: unexpected newline
```

failures with phpstan action. I am having issues nailing down the culprit.

My action: https://github.com/MarcinOrlowski/laravel-api-response-builder/blob/master/.github/workflows/phpstan.yml
Failed run: https://github.com/MarcinOrlowski/laravel-api-response-builder/actions/runs/956572500

Any hints appreciated.

**Comment by g105b** [comment]
Hmm, not sure exactly what the issue is you're facing, but I'll take a look into it in depth tonight when I'm dealing with the other two issues opened today.

**Comment by MarcinOrlowski** [comment]
Please do not waste too much time on this one. It works now so most likely momentary hiccup elsewhere? Anyway. It works. Thanks for PHP action

**Comment by g105b** [comment]
Interesting. I'll still look into your report, because if it's anything I can improve I'm interested in keeping things working well for people.
